# Generated by Django 2.2.7 on 2019-12-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airoportinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='newsImage',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
