# Generated by Django 2.2.7 on 2019-12-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airoportinfo', '0003_auto_20191215_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departureFrom',
            field=models.CharField(choices=[('KY', 'Kyiv')], max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('Lviv', 'Lviv'), ('Ternopil', 'Ternopil'), ('Odesa', 'Odesa'), ('Kharkiv', 'Kharkiv'), ('Ivano-Frankivsk', 'Ivano-Frankivsk')], max_length=100),
        ),
    ]
