# Generated by Django 2.2.7 on 2019-12-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20191214_0011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
