# Generated by Django 2.2.7 on 2019-11-23 19:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airoportinfo', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('travelClass', models.CharField(max_length=20)),
                ('seat', models.IntegerField()),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyPrLine', models.BooleanField()),
                ('buyVIP', models.BooleanField()),
                ('buyFood', models.CharField(choices=[('SN', 'a cocktail snack'), ('AP', 'appetizer'), ('SP', 'soup'), ('SL', 'salad'), ('EN', 'entree(chicken, beef, fish, or pasta'), ('CH', 'cheeses with fruits'), ('IC', 'ice cream'), ('NO', 'no food')], default='NO', max_length=100)),
                ('buyWaitRoom', models.BooleanField()),
                ('buyAddLuggage', models.CharField(choices=[('CB', 'checked baggage'), ('CO', 'carry-on')], default='CO', max_length=50)),
                ('buyerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airoportinfo.Flight')),
            ],
        ),
    ]
