# Generated by Django 2.2.7 on 2019-11-23 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('airoportinfo', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='buyerID',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='flight_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='buyer_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_account_id', to='account.Account'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='flightID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_flight_id', to='airoportinfo.Flight'),
        ),
    ]
