# Generated by Django 2.2.7 on 2019-12-13 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20191123_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='buyer_id',
        ),
    ]
