# Generated by Django 2.2.7 on 2019-12-14 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0003_remove_ticket_buyer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='buyer_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
