# Generated by Django 2.2.7 on 2019-12-14 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0004_ticket_buyer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='name',
            new_name='passenger',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='buyer_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
        migrations.AddField(
            model_name='ticket',
            name='buyer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
