# Generated by Django 2.2.7 on 2019-12-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20191214_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='travelClass',
            field=models.CharField(choices=[('EC', 'economy class'), ('BC', 'business class'), ('FC', 'first class')], max_length=20),
        ),
    ]
