# Generated by Django 2.2.7 on 2019-12-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20191214_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='buyAddLuggage',
            field=models.CharField(choices=[('CB', 'checked baggage'), ('CO', 'carry-on'), ('NL', 'no baggage')], default='CO', max_length=50),
        ),
    ]
