# Generated by Django 2.2.7 on 2019-12-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticket_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='bareTicketPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightTo', models.CharField(choices=[('Lviv', 'Lviv'), ('Ternopil', 'Ternopil'), ('Odesa', 'Odesa'), ('Kharkiv', 'Kharkiv'), ('Ivano-Frankivsk', 'Ivano-Frankivsk')], max_length=50)),
                ('priceOfFlight', models.FloatField(default=100)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='travelClass',
            field=models.CharField(choices=[('economy class', 'economy class'), ('business class', 'business class'), ('first class', 'first class')], max_length=20),
        ),
    ]
