# Generated by Django 2.2.7 on 2019-12-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20191215_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_choices', models.CharField(choices=[('SN', 'a cocktail snack'), ('AP', 'appetizer'), ('SP', 'soup'), ('SL', 'salad'), ('EN', 'entree(chicken, beef, fish, or pasta'), ('CH', 'cheeses with fruits'), ('IC', 'ice cream'), ('NO', 'no food')], max_length=50)),
                ('priceOfFood', models.FloatField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Luggage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luggage_choices', models.CharField(choices=[('CB', 'checked baggage'), ('CO', 'carry-on'), ('NL', 'no baggage')], max_length=50)),
                ('priceOfLuggage', models.FloatField(default=100)),
            ],
        ),
    ]
